# Generated by Django 6.0.5 on 2026-05-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('WEBINAR', 'Webinar'), ('WORKSHOP', 'Workshop'), ('CONFERENCE', 'Conference'), ('TRAINING', 'Training'), ('OTHER', 'Other')], max_length=32)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location_type', models.CharField(choices=[('ONLINE', 'Online'), ('IN_PERSON', 'In Person'), ('HYBRID', 'Hybrid')], max_length=16)),
                ('location_address', models.CharField(blank=True, default='', max_length=255)),
                ('online_link', models.URLField(blank=True, default='')),
                ('registration_link', models.URLField(blank=True, default='')),
                ('is_members_only', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('NEWS', 'News'), ('BLOG', 'Blog'), ('PRESS_RELEASE', 'Press Release'), ('STORY', 'Story')], default='NEWS', max_length=32)),
                ('author_name', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('REPORT', 'Report'), ('PUBLICATION', 'Publication'), ('TOOLKIT', 'Toolkit'), ('POLICY_BRIEF', 'Policy Brief'), ('RESEARCH', 'Research'), ('VIDEO', 'Video'), ('OTHER', 'Other')], max_length=32)),
                ('language', models.CharField(default='en', max_length=16)),
                ('countries', models.CharField(blank=True, default='', max_length=255)),
                ('topics', models.CharField(blank=True, default='', max_length=255)),
                ('file_url', models.URLField(blank=True, default='')),
                ('external_url', models.URLField(blank=True, default='')),
                ('published_at', models.DateTimeField()),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
