# Generated by Django 6.0.5 on 2026-05-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='resource',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file_url',
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resource_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('REPORT', 'Report'), ('PUBLICATION', 'Publication'), ('TOOLKIT', 'Toolkit'), ('POLICY_BRIEF', 'Policy Brief'), ('RESEARCH', 'Research'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('OTHER', 'Other')], max_length=32),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='topics',
        ),
        migrations.AddField(
            model_name='resource',
            name='disability_types',
            field=models.ManyToManyField(blank=True, related_name='resources', to='public.disabilitytype'),
        ),
        migrations.AddField(
            model_name='resource',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='resources', to='public.topic'),
        ),
    ]
