# Generated by Django 6.0.5 on 2026-05-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_disabilitytype_topic_remove_resource_countries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='access_level',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('MEMBERS_ONLY', 'Members Only')], default='PUBLIC', max_length=32),
        ),
    ]
