# Generated by Django 6.0.5 on 2026-06-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_resourcefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='disabilitytype',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disabilitytype',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disabilitytype',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disabilitytype',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disabilitytype',
            name='name_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='excerpt_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='excerpt_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='excerpt_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='excerpt_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='excerpt_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_ar',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_fr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_pt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_sw',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_sw',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
