# Generated by Django 6.0.5 on 2026-05-31 12:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forumpost_content'),
        ('public', '0005_resourcefile'),
        ('users', '0006_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('required_points', models.PositiveIntegerField(default=0)),
                ('required_posts', models.PositiveIntegerField(default=0)),
                ('required_solutions', models.PositiveIntegerField(default=0)),
                ('required_streak', models.PositiveIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeletedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('POST', 'Post'), ('THREAD', 'Thread')], max_length=10)),
                ('original_id', models.PositiveIntegerField()),
                ('original_author', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('reason_deleted', models.CharField(max_length=255)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEW_REPLY', 'New Reply'), ('POST_REACTION', 'Post Reaction'), ('MENTION', 'Mentioned'), ('BADGE_EARNED', 'Badge Earned'), ('MOD_ACTION', 'Moderation Action')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam or Advertising'), ('HARASSMENT', 'Harassment'), ('MISINFORMATION', 'Misinformation'), ('OFFENSIVE', 'Offensive Language'), ('COPYRIGHT', 'Copyright Violation'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed'), ('ESCALATED', 'Escalated to Admin')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('action_taken', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('new_threads', models.PositiveIntegerField(default=0)),
                ('new_posts', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ForumTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('thread_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-thread_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('POST_DELETED', 'Post Deleted'), ('THREAD_LOCKED', 'Thread Locked'), ('THREAD_UNLOCKED', 'Thread Unlocked'), ('USER_WARNED', 'User Warned'), ('USER_SUSPENDED', 'User Suspended'), ('USER_UNBANNED', 'User Unbanned'), ('POST_HIDDEN', 'Post Hidden'), ('POST_APPROVED', 'Post Approved'), ('POINTS_ADJUSTED', 'Reputation Adjusted')], max_length=50)),
                ('reason', models.TextField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReputationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('action_type', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_level', models.CharField(choices=[('OFF', 'No Notifications'), ('REPLIES', 'New Replies Only'), ('ALL', 'All Activity')], default='ALL', max_length=10)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-9999)])),
                ('helpful_received', models.PositiveIntegerField(default=0)),
                ('solutions_provided', models.PositiveIntegerField(default=0)),
                ('posts_created', models.PositiveIntegerField(default=0)),
                ('threads_created', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_until', models.DateTimeField(blank=True, null=True)),
                ('ban_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.AlterModelOptions(
            name='forumthread',
            options={'ordering': ['-is_pinned', '-is_featured', '-last_activity']},
        ),
        migrations.RenameField(
            model_name='forumthread',
            old_name='is_locked',
            new_name='is_featured',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='color_tag',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='forum.forumcategory'),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='thread_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged for Review')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='edit_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='insightful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the topic'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='flagged_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='last_activity_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='reply_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='solution_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('SOLVED', 'Solved'), ('LOCKED', 'Locked by Moderator'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='category_type',
            field=models.CharField(choices=[('COUNTRY', 'Country Group'), ('THEMATIC', 'Thematic Group'), ('GENERAL', 'General Group'), ('ANNOUNCEMENT', 'Announcement'), ('EXPERT_ONLY', 'Expert Discussion')], max_length=32),
        ),
        migrations.AlterField(
            model_name='forumreaction',
            name='reaction_type',
            field=models.CharField(choices=[('LIKE', '👍 Helpful'), ('INSIGHTFUL', '💡 Insightful'), ('CELEBRATE', '🎉 Great Answer'), ('DISAGREE', '👎 Disagree')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='forumcategory',
            index=models.Index(fields=['slug'], name='forum_forum_slug_b34cae_idx'),
        ),
        migrations.AddIndex(
            model_name='forumcategory',
            index=models.Index(fields=['category_type'], name='forum_forum_categor_519888_idx'),
        ),
        migrations.AddIndex(
            model_name='forumcategory',
            index=models.Index(fields=['-last_activity'], name='forum_forum_last_ac_283fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['thread', 'approval_status'], name='forum_forum_thread__e499ae_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['author', '-created_at'], name='forum_forum_author__e19f06_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['is_flagged'], name='forum_forum_is_flag_586960_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreaction',
            index=models.Index(fields=['post', 'reaction_type'], name='forum_forum_post_id_86fb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreaction',
            index=models.Index(fields=['user', '-created_at'], name='forum_forum_user_id_dba514_idx'),
        ),
        migrations.AddField(
            model_name='deletedcontent',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumnotification',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumnotification',
            name='related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='forumnotification',
            name='related_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forumthread'),
        ),
        migrations.AddField(
            model_name='forumnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumreport',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='forumreport',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumstats',
            name='top_contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumstats',
            name='top_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forum.forumthread'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='threads', to='forum.forumtag'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['category', '-created_at'], name='forum_forum_categor_e1fd1f_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['slug'], name='forum_forum_slug_3e25d8_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['status'], name='forum_forum_status_917bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['-view_count'], name='forum_forum_view_co_650c24_idx'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='forum.forumthread'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_against', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reputationlog',
            name='related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.forumpost'),
        ),
        migrations.AddField(
            model_name='reputationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threadsubscription',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='forum.forumthread'),
        ),
        migrations.AddField(
            model_name='threadsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.badge'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badge',
            name='users',
            field=models.ManyToManyField(related_name='forum_badges', through='forum.UserBadge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreputation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reputation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deletedcontent',
            index=models.Index(fields=['content_type', '-deleted_at'], name='forum_delet_content_ef3d36_idx'),
        ),
        migrations.AddIndex(
            model_name='forumnotification',
            index=models.Index(fields=['user', 'is_read'], name='forum_forum_user_id_0aab44_idx'),
        ),
        migrations.AddIndex(
            model_name='forumnotification',
            index=models.Index(fields=['user', '-created_at'], name='forum_forum_user_id_fafcda_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreport',
            index=models.Index(fields=['status', '-created_at'], name='forum_forum_status_1ab692_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreport',
            index=models.Index(fields=['post'], name='forum_forum_post_id_a83d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['user', '-created_at'], name='forum_moder_user_id_1ad105_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['action_type'], name='forum_moder_action__66fb4d_idx'),
        ),
        migrations.AddIndex(
            model_name='reputationlog',
            index=models.Index(fields=['user', '-created_at'], name='forum_reput_user_id_344c01_idx'),
        ),
        migrations.AddIndex(
            model_name='reputationlog',
            index=models.Index(fields=['action_type'], name='forum_reput_action__bf80b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='threadsubscription',
            unique_together={('user', 'thread')},
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
    ]
