# Generated by Django 6.0.5 on 2026-06-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_privatemessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='privatemessage',
            new_name='forum_priva_recipie_66e9a2_idx',
            old_name='forum_priva_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='privatemessage',
            new_name='forum_priva_sender__0b22da_idx',
            old_name='forum_priva_sender__idx',
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='description_ar',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='description_fr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='description_pt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='description_sw',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='name_sw',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
