# Generated by Django 6.0.5 on 2026-05-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='how_heard',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('OPD', 'OPD (Organization of Persons with Disabilities)'), ('CSO', 'CSO (Civil Society Organization)'), ('FBO', 'FBO (Faith Based Organization)'), ('GOVERNMENT', 'Government'), ('ACADEMIC', 'Academic / Researcher'), ('PRIVATE', 'Private Sector'), ('INDIVIDUAL', 'Individual')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='customuser',
            name='professional_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
