# Generated by Django 6.0.5 on 2026-05-28 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio_customuser_how_heard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_fr', models.CharField(blank=True, default='', max_length=100)),
                ('name_ar', models.CharField(blank=True, default='', max_length=100)),
                ('name_pt', models.CharField(blank=True, default='', max_length=100)),
                ('name_sw', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(choices=[('EAST_AFRICA', 'East Africa'), ('WEST_AFRICA', 'West Africa'), ('CENTRAL_AFRICA', 'Central Africa'), ('NORTH_AFRICA', 'North Africa'), ('SOUTHERN_AFRICA', 'Southern Africa')], max_length=32)),
                ('lm_office', models.BooleanField(default=False)),
                ('flag_emoji', models.CharField(blank=True, default='', max_length=16)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.country'),
        ),
    ]
