# Generated by Django 6.0.5 on 2026-06-01 14:21

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMember',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Approval',
                'verbose_name_plural': 'Pending Approvals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='accessibility_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_sw',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
